### ISSUE TITLE
Proxy Rewrite - Phase 2

### ISSUE THREAD

**Issue by JasonBristol** [suresttexas00/minecraft-wrapper#22]
Phase 2 encompasses:
- [x] UUID fixes,
- [x] refactoring of packet parsing logic.
- [x] thread safety.
- [x] robust logging.
- [X] further backwards compatibility work between MC versions.
- [ ] proper name change handling.

**Comment by JasonBristol** [comment]
As per @suresttexas00:

> Our naming conventions in wrapper are somewhat confusing because "client" is handing server-bound traffic and server is handling client-bound traffic, the exact opposite of how protocol wiki is written.

We should reverse this to line up with the wiki

**Comment by suresttexas00** [comment]
I'm not sure if these should be renamed.  It's just something that needs bearing in mind when dealing with packets. 
- "Client" _is_ the connection to a client.  Accordingly, it _does_ receive server-bound packets from the client.

- "Server" _is_ the connection to our server.  Accordingly, it receives client-bound packets from the server.  Bear in mind on this point; Every Client has it's own "Server" instance...

Which makes me think, since they are really two sides of the same "coin", perhaps they should share a common class containing a common set of *__init*__ values?

**Comment by suresttexas00** [comment]
Closing this.  The only item left is better described under #61
