### ISSUE TITLE
Potential for broken functionality for plugin uuids?

### ISSUE THREAD

**Issue by suresttexas00** [suresttexas00/minecraft-wrapper#32]
Ben's original wrapper getPlayer().uuid returns a uuid object, which had two consequences:

1) the UUID always had to be stringed for any textual operations:
`player.message("hi, your uuid is: %s!" % str(player.uuid))`

2) the unstringed uuid could be passed to manually send packets:
```
    def _van(self, player, args):
        if permitted(player, "simple.van", self.usePermissions, self.useVanillaBehavior) is False:
            return
        playersonline = self.minecraft.getPlayers()
        playeruuid = player.uuid
        vanisher_name = player.username
        playerleft = False
...
        if len(args) == 0 or playerleft is True:  # remove player from all logged in tab lists
            for playerXX in playersonline:
                if vanisher_name != self.api.minecraft.getPlayer(playerXX).username:
                    self.api.minecraft.getPlayer(playerXX).client.send(self.pkt_playerlist,
                                                                       "varint|varint|uuid", (4, 1, playeruuid))

```

Now, I have not checked how the new code is handling this, but I am concerned if all our MCUUID class is compatible with the packet sending methods for "uuid"..?

**Comment by suresttexas00** [comment]
The obvious thing is to make sure our "uuid" packet sending can take a string uuid and create an object out of it.

**Comment by JasonBristol** [comment]
Yup this should not be impacted by MCUUID, this was one of my main concerns in packet.py. Since MCUUID shares a base class of UUID packet.py is able to access it in the same way.

In regards to string interpolation the old % format operator will automatically coerce a string since you have defined `%s`. MCUUID's base class of UUID has a `__str__` accessor method that formatting can call. 

In my latest commit to patch-2 I have eliminated all explicit string type casts for UUID during formats because of this

**Comment by suresttexas00** [comment]
You've been saying frequently that %s will coerce a string, but I could swear I have had errors in my plugins where I failed to use str() on objects where the contents have some binary component or are not a string or number of some kind, like the UUIDs...   I'll have to keep an eye on that behavior.

**Comment by JasonBristol** [comment]
At face value this is true, if we were to get low level then only objects
with a `__str__` accessor method can be coerced. This method basically says
how to represent the object as a string. Most objects and all primitives
have this method which is why I say this.

For custom objects it can vary depending on the use case. Typically it is
best practice to always implement this class method so you don't have to
str() during formatting. It gets ambiguous when some objects you have to
str() and others you don't.

If you happen to find an example where you can't implicitly cast I would be
interested in seeing it so we can make the appropriate adjustment.

**Comment by suresttexas00** [comment]
I think this can be closed.  If the uuids did not get packed properly, there would have already been console errors stating that.

**Comment by suresttexas00** [comment]
I remember now where that used to cause me the most problem... it was when I would feed a uuid into wrapper storage object (json) as a key or as data... and I would get those dreaded BenBaptist "A string must be passed to the stuff" errors and my storage objects would not periodic save and would wipe out the disk file contents... that was when I started stringing UUIDs in my plugins after that (except when sending it in packets).

**Comment by JasonBristol** [comment]
Haha I enjoyed fixing those error messages, were would never have know
where they were coming from since all accessors across like 6 modules would
throw that message
