### ISSUE TITLE
unresolved reference for log.py?

### ISSUE THREAD

**Issue by suresttexas00** [suresttexas00/minecraft-wrapper#38]
Not sure how this is corrected:

![image](https://cloud.githubusercontent.com/assets/10001762/14469882/aa6c0ae2-00b4-11e6-9554-e31122269eca.png)

**Comment by suresttexas00** [comment]
I am also seeing issues with the TRACE level logging reference

![image](https://cloud.githubusercontent.com/assets/10001762/14469975/0d39db72-00b5-11e6-86c5-3bb7f99fc45c.png)

**Comment by JasonBristol** [comment]
oops I think for errno I forgot an import, regarding TRACe, I am adding a custom level which the logging package allows in a limited fashion. This may be cause for the warning you are seeing as TRACE is not definited in `__init__.py` of the logging package due to its custom nature. This should not cause any issues, but is good to take note of

**Comment by suresttexas00** [comment]
just did a PR on the experimental. FYI
