### ISSUE TITLE
debug logging not working

### ISSUE THREAD

**Issue by suresttexas00** [suresttexas00/minecraft-wrapper#42]
I have set debug = True in wrapper.properties, but debug is not being logged.

**Comment by JasonBristol** [comment]
As per comments in #33, Config.debug and Config.trace are disabled in favor of logging.json which provides a one stop shop for logging configuration. Change the "console" handler level to DEBUG to enable debugging

**Comment by suresttexas00** [comment]
I will include the code to set that based on the wrapper.properties.

**Comment by JasonBristol** [comment]
It is not as straightforward as it seems, this is something I was working on setting up in the future since we need to take care not to break the Logger pipeline.

Also consider the following:

I enable debug in properties, it sets a debug level in logging.json

Now I set the logging level in logging.json to INFO, now properties need to update as well

This is a race condition and breaks the stateless functionality of the logging package. It is safer, more feature rich, and more encapsulated to contain logging options in logging.json only.

**Comment by JasonBristol** [comment]
We should not couple the two and should instead deprecate or remove Config. Debug

**Comment by suresttexas00** [comment]
I see now.. another config file to set.  You know what I am starting to see.. we need to start moving files like this and wrapper.properties into another place; perhaps like /wrapper-data..?

**Comment by suresttexas00** [comment]
I was confused because I found a "trace" item in the wrapper.properties file...

**Comment by JasonBristol** [comment]
I agree, I think we need a centralized area for configuration files, we should only have two configuration files max, and I think down the road I might be able to even combine the two, but want to wait until some of our higher severity bugs are fixed

**Comment by suresttexas00** [comment]
and yes this:
`
encoding = UTF-8
trace = True
` 
was supposed to allow use of alternate codings for foreign servers in json files:
..finally found it.. a PR by @Sasszem https://github.com/benbaptist/minecraft-wrapper/pull/243
